module Bujo
  module FileHandlers
    def self.resolve: () -> untyped

    class PrintHandler
      def call: (untyped file_path) -> untyped
    end

    class ExecuteHandler
      @command: untyped

      def initialize: (untyped command) -> void

      def call: (untyped file_path) -> untyped
    end
  end
end
